<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hotspot_wizard"
 *
 * Auto generated by Extension Builder 2021-10-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Hotspot Wizard',
    'description' => 'This extension provides the hotspot wizard backend module',
    'category' => 'plugin',
    'author' => 'Johannes Seipelt',
    'author_email' => 'johannes.seipelt@3m5.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
